=== NENA911/nrs/src/main/webapp/attic/oldxml/urn/registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (http://www.altova.com) by Brian Dupras (Duprasville) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:nena:xml:namespace:nrs" targetNamespace="urn:nena:xml:namespace:nrs" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="../_support/nrs-registry.xsd"/>
	<xs:complexType name="recordType">
		<xs:sequence>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="registry" type="tns:registryRefType" minOccurs="0"/>
            <xs:element name="references" type="tns:xrefsType" minOccurs="0"/>
            <xs:element name="date" type="xs:date" minOccurs="0"/>
        </xs:sequence>
	</xs:complexType>
	<xs:element name="record" type="tns:recordType"/>
</xs:schema>

=== NENA911/nrs/src/main/webapp/attic/oldxml/registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./registry.xsl"?>
<registry xmlns="urn:nena:xml:namespace:nrs" id="nrs" registrar="nena" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nena:xml:namespace:nrs registry.xsd">
	<title>NENA Registry System</title>
	<created>2009-09-17</created>
	<updated>2009-09-17</updated>
    <registry ref="../nrs">NRS</registry>
	<references>
        <xref type="nena" data="nena_registry_system">70-001</xref>
    </references>
	<registration_rule>NENA Technical Standard Required</registration_rule>
	<description>When developing and deploying technical standards which employ enumerations, or lists of values, where the enumeration or lists can reasonably be expected to change over time as new technology, vendors, service providers or other stakeholders evolve, a known stable way to maintain the current acceptable values in the enumeration or list is required. The values in the enumeration or list are called a registry.</description>
	<note>Creating a registry involves describing the registry to be created, an initial set of assignments (if appropriate), and guidelines on how future assignments are to be made. Registries to be managed by NRS must be created in a full NENA Technical Standard.</note>
	<records>
		<record>
			<value>urn:nena</value>
			<description>The IETF has delegated to NRS the urn:nena namespace.</description>
            <registry ref="urn/nena">urn:nena</registry>
            <references>
                <xref type="rfc" data="rfc6061"/>
            </references>
            <date>2011-01-01</date>
		</record>
		<record>
			<value>elementState</value>
			<description>An enumerated value of the current state of an agency or element</description>
            <registry ref="elementState"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>serviceState</value>
			<description>ServiceState is an event that indicates the state of service either automatically determined, or as determined by management.</description>
            <registry ref="serviceState"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>securityPosture</value>
			<description></description>
            <registry ref="securityPosture"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>ExternalEvenetCodes</value>
			<description></description>
            <registry ref="ExternalEventCodes">ExternalEventCodes</registry>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>EsrpNotifyEventCodes</value>
			<description></description>
            <registry ref="EsrpNotifyEventCodes">EsrpNotifyEventCodes</registry>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>RouteCause</value>
			<description></description>
            <registry ref="RouteCause"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>LogEvent</value>
			<description></description>
            <registry ref="LogEvent"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>AgencyRoles</value>
			<description></description>
            <registry ref="AgencyRoles"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>AgentRoles</value>
			<description></description>
            <registry ref="AgentRoles"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>ServiceDeliveredByProviderToEndUser</value>
			<description></description>
            <registry ref="ServiceDeliveredByProviderToEndUser"/>
            <references>
                <xref type="nena" data="i3_Stage3">08-003 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>DeviceClassification</value>
			<description></description>
            <registry ref="DeviceClassification"/>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2009-09-17</date>
		</record>
		<record>
			<value>DeviceManufacturer</value>
			<description></description>
            <registry ref="DeviceManufacturer"/>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2009-09-17</date>
		</record>
		<record>
			<value>TypeOfDeviceIdentifier</value>
			<description></description>
            <registry ref="TypeOfDeviceIdentifier"/>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2009-09-17</date>
		</record>
		<record>
			<value>DeviceSpecificSchema</value>
			<description></description>
            <registry ref="DeviceSpecificSchema"/>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2009-09-17</date>
		</record>
		<record>
			<value>StreetPrePostModifiers</value>
			<description></description>
            <registry ref="StreetPrePostModifiers"/>
            <references>
                <xref type="uri" data="https://nena.webexone.com/r.asp?a=5&amp;id=118741">NENA 71-002 Draft</xref>
            </references>
            <date>2011-01-19</date>
		</record>
		<record>
			<value>StreetPrefixSuffix</value>
			<description></description>
            <registry ref="StreetPrefixSuffix"/>
            <references>
                <xref type="uri" data="https://nena.webexone.com/r.asp?a=5&amp;id=118741">NENA 71-002 Draft</xref>
            </references>
            <date>2011-01-19</date>
		</record>
		<record>
			<value>ManagementPolicy</value>
			<description>NRS Management Policies</description>
            <registry ref="ManagementPolicy"/>
            <references>
                <xref type="nena" data="nena_registry_system">70-001</xref>
            </references>
            <date>2009-09-17</date>
		</record>
	</records>
</registry>

=== NENA911/nrs/src/main/webapp/attic/oldxml/DeviceClassification/registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./registry.xsl"?>
<registry xmlns="urn:nena:xml:namespace:nrs" id="elementState" registrar="nena" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:nena:xml:namespace:nrs registry.xsd">
	<title>DeviceClassification</title>
	<created>2009-09-17</created>
	<updated>2009-09-17</updated>
    <registry ref="../../nrs">NRS</registry>
    <references>
        <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
    </references>
	<registration_rule>NENA Technical Standard Required</registration_rule>
	<description>If the device provides the data structure, the device information should be provided. If the Service Provider provides the structure and it knows what the device is, the Service
	Provider should provide the device information. Often the carrier does not know what the device is. It is possible to receive 2 data structures, one created by the device and one created by the Service Provider.   Information about the device, not how itâ€™s being used.
	</description>
	<note>A new entry to DeviceClassification requires a description of the value, and justification for adding a new classification.  Requires an update to NENA 71-001.</note>
	<records>
		<record>
			<value>Cordless handset</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Fixed phone</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Mobile handset</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>ATA</value>
			<description>Analog Terminal Adapter</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Satellite phone</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Stationary computing device</value>
			<description>Alarm system, data sensor, etc.</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Guardian devices</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Desktop PC</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Laptop computing device</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Tablet computing device</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Alarm System</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Data sensor</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Personal beacons</value>
			<description>SPOT, etc.</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Auto telematics</value>
			<description>Indicates VEDS dataset.</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Trucking telematics</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Marine telematics</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Personal Digital Assistant</value>
			<description>PDA</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Personal Navigation Device</value>
			<description>PND</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Smart phone</value>
			<description>Blackberry, PDAs</description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Internet tablet</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Gaming console</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Video phone</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Other text device</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
		<record>
			<value>Not available</value>
			<description></description>
            <references>
                <xref type="nena" data="NG911_AdditionalData">71-001 v1</xref>
            </references>
            <date>2011-06-14</date>
		</record>
    </records>
</registry>
